
package ua.myclient.taxi.service;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ExceptionMessage", targetNamespace = "http://service.taxi.myClient.ua/")
public class ExceptionMessage_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExceptionMessage faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExceptionMessage_Exception(String message, ExceptionMessage faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ExceptionMessage_Exception(String message, ExceptionMessage faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: ua.myclient.taxi.service.ExceptionMessage
     */
    public ExceptionMessage getFaultInfo() {
        return faultInfo;
    }

}
