
package ua.myclient.taxi.service;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Taxi", targetNamespace = "http://service.taxi.myClient.ua/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ua.myclient.taxi.service.ObjectFactory.class,
    ua.myclient.taxi.service.driver.ObjectFactory.class,
    ua.myclient.taxi.service.order.ObjectFactory.class,
    ua.myclient.taxi.service.user.ObjectFactory.class
})
public interface Taxi {


    /**
     * 
     * @param parameters
     * @return
     *     returns ua.myclient.taxi.service.HistoryResp
     */
    @WebMethod(action = "get")
    @WebResult(name = "HistoryResp", targetNamespace = "http://service.taxi.myClient.ua/", partName = "parameters")
    @Action(input = "get", output = "http://service.taxi.myClient.ua/Taxi/getUsersOrderHistoryResponse")
    public HistoryResp getUsersOrderHistory(
        @WebParam(name = "HistoryReq", targetNamespace = "http://service.taxi.myClient.ua/", partName = "parameters")
        HistoryReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ua.myclient.taxi.service.DriverByCodeResp
     */
    @WebMethod(action = "get")
    @WebResult(name = "DriverByCodeResp", targetNamespace = "http://service.taxi.myClient.ua/", partName = "parameters")
    @Action(input = "get", output = "http://service.taxi.myClient.ua/Taxi/getDriverByCodeResponse")
    public DriverByCodeResp getDriverByCode(
        @WebParam(name = "DriverByCodeReq", targetNamespace = "http://service.taxi.myClient.ua/", partName = "parameters")
        DriverByCodeReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ua.myclient.taxi.service.CrateResp
     * @throws ExceptionMessage_Exception
     */
    @WebMethod(action = "create")
    @WebResult(name = "CrateResp", targetNamespace = "http://service.taxi.myClient.ua/", partName = "parameters")
    @Action(input = "create", output = "http://service.taxi.myClient.ua/Taxi/createOrderResponse", fault = {
        @FaultAction(className = ExceptionMessage_Exception.class, value = "http://service.taxi.myClient.ua/Taxi/createOrder/Fault/ExceptionMessage")
    })
    public CrateResp createOrder(
        @WebParam(name = "CreateReq", targetNamespace = "http://service.taxi.myClient.ua/", partName = "parameters")
        CreateReq parameters)
        throws ExceptionMessage_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns ua.myclient.taxi.service.HistoryAboveMarkResp
     */
    @WebMethod(action = "get")
    @WebResult(name = "HistoryAboveMarkResp", targetNamespace = "http://service.taxi.myClient.ua/", partName = "parameters")
    @Action(input = "get", output = "http://service.taxi.myClient.ua/Taxi/getHistoryAboveMarkResponse")
    public HistoryAboveMarkResp getHistoryAboveMark(
        @WebParam(name = "HistoryAboveMarkReq", targetNamespace = "http://service.taxi.myClient.ua/", partName = "parameters")
        HistoryAboveMarkReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ua.myclient.taxi.service.HistoryBelowMarkResp
     */
    @WebMethod(action = "get")
    @WebResult(name = "HistoryBelowMarkResp", targetNamespace = "http://service.taxi.myClient.ua/", partName = "parameters")
    @Action(input = "get", output = "http://service.taxi.myClient.ua/Taxi/getHistoryBelowMarkResponse")
    public HistoryBelowMarkResp getHistoryBelowMark(
        @WebParam(name = "HistoryBelowMarkReq", targetNamespace = "http://service.taxi.myClient.ua/", partName = "parameters")
        HistoryBelowMarkReq parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns ua.myclient.taxi.service.DriverBySurnameResp
     */
    @WebMethod(action = "get")
    @WebResult(name = "DriverBySurnameResp", targetNamespace = "http://service.taxi.myClient.ua/", partName = "parameters")
    @Action(input = "get", output = "http://service.taxi.myClient.ua/Taxi/getDriverBySurnameResponse")
    public DriverBySurnameResp getDriverBySurname(
        @WebParam(name = "DriverBySurnameReq", targetNamespace = "http://service.taxi.myClient.ua/", partName = "parameters")
        DriverBySurnameReq parameters);

}
